### ISSUE TITLE
Missing image in /creators/Decorating_the_Workflow_fixed.tex

### ISSUE THREAD

**Issue by mlpgwdg** [snakemake/snakemake-hpc-teaching-material#103]
In /creators/Decorating_the_Workflow_fixed.tex , there's an included image around line number 392 stating:

\includegraphics[width=0.9\textwidth]{filesystem/overview.png}

Said image seems to not exist in the image folder of the repository, and I was not able to find an obvious replacement candidate so I can't fix this with a simple commit.

**Comment by cmeesters** [comment]
thanks for reporting, see PR #104 - I _really_ do not understand, how this can happen, as all PRs undergo a CI

**Comment by cmeesters** [comment]
done
